typography_spectrum: 0.23811
color:
  brandColors:
    - '#ffffff'
    - '#321448'
    - '#d8d8d8'
    - '#b7b7b7'
    - '#736284'
  brandStrength: 0.5417916581500322
  lightness: 0.073954634135589
  saturation: 0.33145853178575635
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24221
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Renich Bon Ciric
  email: renich@evalinux.com
  url: evalinux.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/55666401-e745-4d63-81c8-5c4f2573956e.svg
name: EVALinux
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 3b1662b3-a5cc-464e-842c-69e967fd7449
    type: content
  - name: About us
    id: 2d05761f-2246-47d9-8271-4b8fe0dd989a
    type: content
  - name: Services
    id: 6f8184eb-1720-4dbe-8025-8f302b2bec09
    type: content
favicon: null
title: EVALinux | Official Website
description: When 'just works' is not enough
purpose: []
